name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t rzrmayur/fastapi-ci-demo:${{ github.run_number }} .

      - name: Push Docker image
        run: docker push rzrmayur/fastapi-ci-demo:${{ github.run_number }}
